name: discord_bot
description: Bot Discord pentru Maniak Shop cu sistem de tickete
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  nyxx: ^6.5.2
  nyxx_commands: ^6.0.4
  dotenv: ^2.3.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^4.0.0